name: eGK library develop CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Extract version information
      run: |
        majorEgkAndroid=$(awk -F "=" '/majorEgkAndroid/ {print $2}' gradle/libs.versions.toml | xargs)
        echo "Extracted majorSdk: $majorEgkAndroid"
        minorEgkAndroid=$(awk -F "=" '/minorEgkAndroid/ {print $2}' gradle/libs.versions.toml | xargs)
        echo "Extracted minorSdk: $minorEgkAndroid"
        patchEgkAndroid=$(awk -F "=" '/patchEgkAndroid/ {print $2}' gradle/libs.versions.toml | xargs)
        echo "Extracted patchSdk: $patchEgkAndroid"
        echo "MAJOR_EGK_API_VERSION=$majorEgkAndroid" >> $GITHUB_ENV
        echo "MINOR_EGK_API_VERSION=$minorEgkAndroid" >> $GITHUB_ENV
        echo "PATCH_EGK_API_VERSION=$patchEgkAndroid" >> $GITHUB_ENV
        echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_ENV
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean :egk:assembleRelease
    - name: Upload AAR
      uses: actions/upload-artifact@v2
      with:
        name: link4health-egk-library${{ env.MAJOR_EGK_API_VERSION }}.${{ env.MINOR_EGK_API_VERSION }}.${{ env.PATCH_EGK_API_VERSION }}-#${{ github.run_number }}-${{ env.SHORT_SHA }}
        path: egk/build/outputs/aar/*.aar