name: Build and publish EGK SNAPSHOT

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  id-token: write  # Required for Google Cloud workload identity federation

jobs:
  develop:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout EGK
        uses: actions/checkout@v7
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Set up git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: Set up Android SDK
        uses: android-actions/setup-android@v4
        with:
          packages: ''

      - name: Install Android SDK
        run: sdkmanager "platform-tools" "platforms;android-35"

      - name: Extract version information
        run: |
          majorEgkAndroid=$(grep '^\s*majorEgkAndroid\s*=' gradle.properties | sed 's/.*=\s*//')
          echo "Extracted majorSdk: $majorEgkAndroid"
          minorEgkAndroid=$(grep '^\s*minorEgkAndroid\s*=' gradle.properties | sed 's/.*=\s*//')
          echo "Extracted minorSdk: $minorEgkAndroid"
          patchEgkAndroid=$(grep '^\s*patchEgkAndroid\s*=' gradle.properties | sed 's/.*=\s*//')
          echo "Extracted patchSdk: $patchEgkAndroid"
          echo "MAJOR_EGK_API_VERSION=$majorEgkAndroid" >> $GITHUB_ENV
          echo "MINOR_EGK_API_VERSION=$minorEgkAndroid" >> $GITHUB_ENV
          echo "PATCH_EGK_API_VERSION=$patchEgkAndroid" >> $GITHUB_ENV
          echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_ENV

      - name: Cache Gradle packages
        uses: actions/cache@v6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/gradle.properties
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: 'Authenticate to Google Cloud'
        id: auth
        uses: google-github-actions/auth@v3
        with:
          token_format: access_token
          project_id: "${{ vars.ARTIFACT_GOOGLE_PROJECT }}"
          workload_identity_provider: "${{ vars.ARTIFACT_GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}"
          service_account:  "${{ vars.ARTIFACT_GOOGLE_SERVICE_ACCOUNT }}"

      - name: Create gradle.properties
        run: |
          mkdir -p ~/.gradle
          echo "nvdApiKey=${{ secrets.NVD_API_KEY }}" >> ~/.gradle/gradle.properties
          echo "org.gradle.internal.publish.checksums.insecure=true" >> ~/.gradle/gradle.properties
          echo "googleArtifactRegistryUrl=https://${{ vars.ARTIFACT_REGISTRY_LOCATION }}-maven.pkg.dev/${{ vars.ARTIFACT_GOOGLE_PROJECT }}/${{ vars.ARTIFACT_REGISTRY_REPOSITORY }}" >> ~/.gradle/gradle.properties
          echo "googleArtifactRegistryAccessToken=${{ steps.auth.outputs.access_token }}" >> ~/.gradle/gradle.properties

      - name: Build EGK SNAPSHOT
        run: |
          ./gradlew clean :egk:assembleDebug



      - name: Publish EGK SNAPSHOT
        run: |
          ./gradlew :egk:publishLink4HealthEgkLibraryPublicationToGoogleArtifactRegistryRepository
