# Workflow for deploying documentation and reports to GitHub Pages
name: Deploy Documentation and Reports to Pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Triggered when the "Release build and publish ApiShared" workflow completes
  workflow_run:
    workflows: [ "Build and publish Egk Release" ]
    types:
      - completed

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write  # Permissions to create and manage pull requests

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job for deploying documentation and reports
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages  # Checkout the gh-pages branch
          fetch-depth: 0

      - name: Generate Documentation Index HTML
        run: ./gradlew generateDocIndexHtml

      - name: Prepare updated documentation in gh-pages branch
        run: |
          rsync -av --delete docs/ ./  # copy contents of docs directory to the root of gh-pages branch

      - name: Commit and push changes
        run: |
          git add -A
          git commit -m "Update generated documentation"
          git push origin gh-pages
