name: Create Release for eGK library
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Extract version information
        run: |
          majorEgkAndroid=$(awk -F "=" '/majorEgkAndroid/ {print $2}' gradle/libs.versions.toml | xargs)
          echo "Extracted majorSdk: $majorEgkAndroid"
          minorEgkAndroid=$(awk -F "=" '/minorEgkAndroid/ {print $2}' gradle/libs.versions.toml | xargs)
          echo "Extracted minorSdk: $minorEgkAndroid"
          patchEgkAndroid=$(awk -F "=" '/patchEgkAndroid/ {print $2}' gradle/libs.versions.toml | xargs)
          echo "Extracted patchSdk: $patchEgkAndroid"
          echo "MAJOR_EGK_API_VERSION=$majorEgkAndroid" >> $GITHUB_ENV
          echo "MINOR_EGK_API_VERSION=$minorEgkAndroid" >> $GITHUB_ENV
          echo "PATCH_EGK_API_VERSION=$patchEgkAndroid" >> $GITHUB_ENV
          echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_ENV
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean assembleRelease

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        with:
          tag_name: Release-${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: egk/build/outputs/aar/link4health-egk-library-${{ env.MAJOR_EGK_API_VERSION }}.${{ env.MINOR_EGK_API_VERSION }}.${{ env.PATCH_EGK_API_VERSION }}-${{ env.SHORT_SHA }}.aar
          asset_name: link4health-egk-library-${{ env.MAJOR_EGK_API_VERSION }}.${{ env.MINOR_EGK_API_VERSION }}.${{ env.PATCH_EGK_API_VERSION }}-#${{ github.run_number }}-${{ env.SHORT_SHA }}
          asset_content_type: application/zip